### PR TITLE
LogHandler circuit breaker

### PR DESCRIPTION
**Pull request by slacAWallace**
fbSocket will spew errors if anything about the initial setup is wrong (missing license, missing module, etc.)

This should prevent PLC DoSing.

### CODE REVIEW

**Comment by klauer** [comment]
Think we could have it try again after a certain period of time?

**Comment by slacAWallace** [comment]
It can retry if the reset is pressed.

**Comment by slacAWallace** [comment]
What I mean is, making it more automatic is a bit more work, and I think the case where it being more automatic will be hard to hit most of the time. If it can't get a handle it's probably because the PLC needs to be reactivated with the new module and or license.

**Comment by klauer** [comment]
I worry that a misconfiguration may hide a ton of log messages that we would want to see eventually. How can we make this blow up enough so that it gets fixed but not enough to be a DoS?

**Comment by slacAWallace** [comment]
We can make it stop the PLC.

**Comment by slacAWallace** [comment]
@klauer how's it look?

**Pull request merged**
