### PR TITLE
DEV: For FB_LREALFromEPICS, Added Logging and bValid 2 second buffer to deal with blips.

### PR DESCRIPTION
**Pull request by slacAdpai**

### CODE REVIEW

**Comment by slacAdpai** [comment]
Fixes #45

**Comment by klauer** [comment]
We chatted on zoom about this, but:
1. I think we could add the logging functionality in the `FB_LREALFromEPICS`
2. @slacAWallace is going to tweak this FB to mirror the value in the PLC back to EPICS via the `_RBV`
3. I think your proposed severity functionality could exist in a separate function block - perhaps you should test it in your project and then if it fixes the issue, we can merge it in to twincat-general?

**Comment by slacAdpai** [comment]
> We chatted on zoom about this. To summarize:
> 
> 1. I think we could add the logging functionality in the `FB_LREALFromEPICS`
> 2. @slacAWallace is going to tweak this FB to mirror the value in the PLC back to EPICS via the `_RBV`
> 3. I think your proposed severity functionality could exist in a separate function block - perhaps you should test it in your project and then if it fixes the issue, we can merge it in to twincat-general?

Ken, thank you for the summary!

**Comment by klauer** [comment]
Made a brief issue in #51 so we can close this and move forward.

**Pull request closed without merging**
