### PR TITLE
MAINT: address static analysis messages, drop tmc

### LINKED ISSUE #75: Work through the static analysis errors that prevent running the test suite
## Current Behavior

from the WIP Jenkins CI:
```
2023-05-25 12:29:38 [INFO ] - Building solution...
2023-05-25 12:29:46 [ERROR] - Description: SA0027: Object name 'ST_PortAddr' already used in Library 'tc2_ethercat, 3.3.21.0 (beckhoff automation gmbh)'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Diagnostics\DUT\ST_PortAddr.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0027: Variable name 'Init' in 'AutoReset' already used for an object in Library 'tc3_eventlogger, 3.1.33.0 (beckhoff automation gmbh)'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\Tests\FB_CircuitBreaker_Test.TcPOU;FB_CircuitBreaker_Test.AutoReset
2023-05-25 12:29:46 [ERROR] - Description: SA0027: Variable name 'test' in 'FB_EtherCATDiag' already used for an object in Library 'tcunit, 1.2.1.0 (www.tcunit.org)'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Diagnostics\FB_EtherCATDiag.TcPOU
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'DisarmCountDefault'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\FB_LogHandler.TcPOU
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'ESC_MAX_PORTS'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\GVLs\Global_Variables_EtherCAT.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'fTimeStamp'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\GVLs\DefaultGlobals.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'iSLAVEADDR_ARR_SIZE'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\GVLs\Global_Variables_EtherCAT.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'I_EcatMaster1'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'LogToVisualStudio'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\FB_Listener.TcPOU;FB_Listener.LogToVisualStudio.Set
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'MAX_STATES'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\GVLs\GeneralConstants.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'nTotalEvents'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\FB_LogMessage.TcPOU
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'nTrickleThreshold'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\GVL_Logger.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'stEventInfo'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\FB_Listener.TcPOU
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'stSys'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\GVLs\DefaultGlobals.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'TCPADS_MAXUDP_BUFFSIZE'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\POUs\Logger\GVL_Logger.TcGVL
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'xAtVacuum'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'xFirstScan'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'xIOState'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'xOverrideMode'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Description: SA0033: Unused Variable 'xSwAlmRst'
2023-05-25 12:29:46 [ERROR] - ErrorLevel: vsBuildErrorLevelHigh
2023-05-25 12:29:46 [ERROR] - Filename: c:\Jenkins\workspace\lcls-twincat-general\LCLSGeneral\LCLSGeneral\Data types\Misc\ST_System.TcDUT
2023-05-25 12:29:46 [ERROR] - Build errors in project
```

## Expected Behavior

We should be able to build the project and run the unit tests with no modifications

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Work through all rest of the static analysis build failures, following on from @sagatowski 's edits in #74 

  - For some of these, I opted to delete the variable, e.g. when it was an internal `VAR` that never was used (or, is no longer used at present)
  - For others, I opted to ignore the warning, e.g. when it was a global that may be in use elsewhere or a property that can be set to and read from inside a plc project
  - I tried to be careful here but a second opinion is good
- Drop the tmc file, it isn't used in this context and generally just makes the diffs awful
- Update the .gitignore with our confluence link and refresh the list here

## Motivation and Context

closes #75 
Once merged, I get to see if the Jenkins pipeline runs all the way through (have not figured out PR config yet)

## How Has This Been Tested?

The TcUnit tests build and pass now without modifying the project
image

## Where Has This Been Documented?

N/A

## Pre-merge checklist
- [x] Code works interactively
- [x] Code contains descriptive comments
- [x] Test suite passes locally
- [x] Libraries are set to ``Always Newest`` version (``Library, *``)
- [x] Committed with ``pre-commit`` or ran ``pre-commit run --all-files``

### CODE REVIEW

**Review by klauer — APPROVED** [review]
LGTM

Bug in CI checking the syntax of a deleted file: 🤦 

`LCLSGeneral/LCLSGeneral/POUs/Diagnostics/DUT/ST_PortAddr.TcDUT`
And that's causing the syntax checker to fail

**Comment by ZLLentz** [comment]
Oops!

(For the record, I deleted that file because there is an identical structure with the same name in Tc2_Ethercat)

**Comment by ZLLentz** [comment]
Ok, I feel good about this so I'm merging with just one review. We can revise these later if there was a good reason for any of the things I removed.
I also just really want to see the jenkins pipeline run

**Comment by ZLLentz** [comment]
Huh, apparently the tmc was functional in this project as per #14, so I'll need to make a follow-up PR
Locally the build still succeeded because, despite no longer being tracked, I hadn't deleted the tmc file

On CI the project doesn't build at all

**Comment by klauer** [comment]
Argghh, the event classes! You asked me specifically about the tmc and I had forgotten - sorry, @ZLLentz...

**Comment by ZLLentz** [comment]
The good news is that the CI pipeline catches these things

**Comment by ZLLentz** [comment]
I'm personally somewhat surprised that TwinCAT relies on what is nominally a built file for things like this, seems unstable

**Comment by sagatowski** [comment]
I'm copy-pasting what I wrote in #74:
@ZLLentz & @klauer The reason I did a reverted commit is because the TMC-file is functional in your application. For some reason (don't know why, and didn't even know it was possible), the events are stored in your TMC-file. So this file needs to be there, otherwise you won't be able to build!

What I normally do for projects that use the Tc3_EventLogger is to make sure to store them in a separate file, which is possible to do in TwinCAT. You basically create a separate type in the type system where you store your events, and then you exclude ONLY THAT file in your gitignore but ignore all other TMC-files. Then you don't get the annoying behaviour of a changing TMC-file for every re-compilation.

So if you create a separate type system class (TMC):
image
Then you get all your events here:
image


Then you can ignore ALL tmc-files except this one (this will remove the annoying tmc-file that changes everytime you do a compilation).

**Comment by ZLLentz** [comment]
That's a really helpful trick, I'll try it

**Pull request merged**
